old_sound_rabbit_mq:
  connections:
    default:
      host: "localhost"
      port: 5672
      user: "guest"
      password: "guest"
      vhost: "/"
      lazy: true
      connection_timeout: 3
      read_write_timeout: 3

  producers:
    reservation_notification:
      connection: default
      exchange_options:
        name: "reservation_notifications"
        type: direct

  consumers:
    reservation_notification:
      connection: default
      exchange_options:
        name: "reservation_notifications"
        type: direct
      queue_options:
        name: "reservation_notifications"
      callback: App\Consumer\ReservationNotificationConsumer
